# **Business Understanding**

**Breast Cancer Wisconsin (Original)**
Samples arrive periodically as Dr. Wolberg reports his clinical cases. The database therefore reflects this chronological grouping of the data. This grouping information appears immediately below, having been removed from the data itself:

Group 1: 367 instances (January 1989)
Group 2:  70 instances (October 1989)
Group 3:  31 instances (February 1990)
Group 4:  17 instances (April 1990)
Group 5:  48 instances (August 1990)
Group 6:  49 instances (Updated January 1991)
Group 7:  31 instances (June 1991)
Group 8:  86 instances (November 1991)
-----------------------------------------
Total:   699 points (as of the donated datbase on 15 July 1992)

Note that the results summarized above in Past Usage refer to a dataset of size 369, while Group 1 has only 367 instances.  This is because it originally contained 369 instances; 2 were removed.  The following statements summarizes changes to the original Group 1's set of data:

#####  Group 1 : 367 points: 200B 167M (January 1989)

#####  Revised Jan 10, 1991: Replaced zero bare nuclei in 1080185 & 1187805

#####  Revised Nov 22,1991: Removed 765878,4,5,9,7,10,10,10,3,8,1 no record
#####                  : Removed 484201,2,7,8,8,4,3,10,3,4,1 zero epithelial
#####                  : Changed 0 to 1 in field 6 of sample 1219406
#####                  : Changed 0 to 1 in field 8 of following sample:
#####                  : 1182404,2,3,1,1,1,2,0,1,1,1

Has Missing Values? Yes

*Variables*
1. Sample code number:            id number
2. Clump Thickness:               1 - 10
3. Uniformity of Cell Size:       1 - 10
4. Uniformity of Cell Shape:      1 - 10
5. Marginal Adhesion:             1 - 10
6. Single Epithelial Cell Size:   1 - 10
7. Bare Nuclei:                   1 - 10
8. Bland Chromatin:               1 - 10
9. Normal Nucleoli:               1 - 10
10. Mitoses:                       1 - 10
11. Class:                        (2 for benign, 4 for malignant)

[Data Source](https://archive.ics.uci.edu/dataset/15/breast+cancer+wisconsin+original)

Loading Libraries

In [52]:
import pandas as pd # data manipulation and reading the dat as a dataframe
import numpy as np # for numerical analysis 
import seaborn as sns # visualizations
from sklearn.model_selection import train_test_split # we split the data to use it well 
from sklearn.metrics import r2_score # evaluation metric  - R^2 
import matplotlib.pyplot as plt # aids in visualization
from sklearn.datasets import load_iris # preloaded data
from sklearn.linear_model import LogisticRegression # the model itself
from sklearn.preprocessing import StandardScaler # scaling towards a mean = 0 and sd = 1

In [53]:
#### **Loading Data**

In [54]:
columns = [
"ID",
"Clump_thickness",
"Uniformity_of_cell_size",
"Uniformity_of_cell_shape",
"Marginal_adhesion",
"Single_epithelial_cell_size",
"Bare_nuclei",
"Bland_chromatin",
"Normal_nucleoli",
"Mitoses",
"Diagnosis"
]

In [55]:
df = pd.read_csv(r"..\data\abalone.data", header=None, names = columns)

In [56]:
df.columns

Index(['ID', 'Clump_thickness', 'Uniformity_of_cell_size',
       'Uniformity_of_cell_shape', 'Marginal_adhesion',
       'Single_epithelial_cell_size', 'Bare_nuclei', 'Bland_chromatin',
       'Normal_nucleoli', 'Mitoses', 'Diagnosis'],
      dtype='str')

In [57]:
df.head(3)

,ID,Clump_thickness,Uniformity_of_cell_size,Uniformity_of_cell_shape,Marginal_adhesion,Single_epithelial_cell_size,Bare_nuclei,Bland_chromatin,Normal_nucleoli,Mitoses,Diagnosis
0,M,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.15,15,NaN,NaN
1,M,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.07,7,NaN,NaN
2,F,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.21,9,NaN,NaN

# **Data Understanding**

In [58]:
df.shape

(4177, 11)

In [59]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4177 entries, 0 to 4176
Data columns (total 11 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ID                           4177 non-null   str
 1   Clump_thickness              4177 non-null   float64
 2   Uniformity_of_cell_size      4177 non-null   float64
 3   Uniformity_of_cell_shape     4177 non-null   float64
 4   Marginal_adhesion            4177 non-null   float64
 5   Single_epithelial_cell_size  4177 non-null   float64
 6   Bare_nuclei                  4177 non-null   float64
 7   Bland_chromatin              4177 non-null   float64
 8   Normal_nucleoli              4177 non-null   int64
 9   Mitoses                      0 non-null      float64
 10  Diagnosis                    0 non-null      float64
dtypes: float64(9), int64(1), str(1)
memory usage: 363.2 KB

In [70]:
df['Bare_nuclei'].unique()

array([1.010e-01, 4.850e-02, 1.415e-01, 1.140e-01, 3.950e-02, 7.750e-02,
       1.495e-01, 1.125e-01, 1.510e-01, 1.475e-01, 8.100e-02, 9.500e-02,
       1.710e-01, 8.050e-02, 1.330e-01, 8.700e-02, 4.300e-02, 7.500e-02,
       6.200e-02, 4.900e-02, 2.140e-01, 2.100e-01, 3.010e-01, 1.880e-01,
       2.720e-01, 2.340e-01, 2.190e-01, 2.270e-01, 2.420e-01, 2.805e-01,
       3.575e-01, 3.925e-01, 4.115e-01, 1.240e-01, 3.075e-01, 1.165e-01,
       2.035e-01, 8.600e-02, 9.100e-02, 1.960e-01, 2.350e-02, 1.500e-02,
       1.250e-02, 4.500e-02, 1.100e-01, 2.550e-02, 2.135e-01, 1.110e-01,
       6.000e-02, 9.600e-02, 1.055e-01, 9.150e-02, 1.755e-01, 9.550e-02,
       1.200e-01, 1.400e-02, 1.300e-01, 1.600e-01, 1.935e-01, 8.000e-02,
       1.315e-01, 1.015e-01, 2.240e-01, 1.155e-01, 4.050e-02, 1.680e-01,
       9.850e-02, 2.250e-01, 2.610e-01, 2.895e-01, 2.210e-01, 1.890e-01,
       1.940e-01, 1.595e-01, 2.355e-01, 2.520e-01, 1.920e-01, 2.160e-01,
       2.225e-01, 2.050e-01, 2.075e-01, 2.310e-01, 1.675e-01, 1.525e-01,
       2.540e-01, 3.180e-01, 3.425e-01, 3.880e-01, 1.385e-01, 1.320e-01,
       8.500e-02, 4.600e-02, 1.915e-01, 1.640e-01, 2.405e-01, 1.835e-01,
       1.830e-01, 1.790e-01, 9.800e-02, 1.345e-01, 1.070e-01, 6.350e-02,
       6.300e-02, 1.460e-01, 1.585e-01, 1.020e-01, 1.720e-01, 5.950e-02,
       1.035e-01, 5.750e-02, 1.725e-01, 5.100e-02, 5.050e-02, 5.450e-02,
       6.100e-02, 2.635e-01, 2.830e-01, 3.600e-02, 5.600e-02, 2.050e-02,
       3.450e-02, 2.950e-02, 2.055e-01, 1.435e-01, 3.060e-01, 1.900e-01,
       1.075e-01, 1.080e-01, 3.900e-02, 6.500e-03, 8.000e-03, 2.620e-01,
       2.585e-01, 3.050e-01, 1.310e-01, 2.425e-01, 2.615e-01, 1.785e-01,
       2.475e-01, 2.575e-01, 2.970e-01, 3.980e-01, 4.830e-01, 4.515e-01,
       4.080e-01, 3.085e-01, 4.090e-01, 5.410e-01, 1.690e-01, 2.330e-01,
       1.845e-01, 1.800e-02, 3.700e-02, 3.750e-02, 4.750e-02, 2.165e-01,
       2.000e-01, 2.660e-01, 2.680e-01, 3.670e-01, 2.965e-01, 3.360e-01,
       3.315e-01, 3.350e-01, 2.710e-01, 1.815e-01, 1.965e-01, 1.535e-01,
       1.450e-01, 1.780e-01, 2.130e-01, 1.465e-01, 1.550e-01, 7.100e-02,
       1.085e-01, 6.700e-02, 1.685e-01, 5.200e-02, 1.625e-01, 4.150e-02,
       7.850e-02, 1.355e-01, 1.280e-01, 1.635e-01, 7.000e-02, 1.150e-01,
       7.550e-02, 1.235e-01, 1.440e-01, 1.250e-01, 8.200e-02, 2.095e-01,
       1.580e-01, 1.930e-01, 2.870e-01, 2.900e-02, 8.300e-02, 3.200e-02,
       5.000e-04, 3.000e-03, 2.000e-03, 4.500e-03, 2.185e-01, 2.450e-02,
       1.050e-02, 2.650e-02, 3.250e-02, 3.800e-02, 3.500e-02, 2.170e-01,
       2.775e-01, 2.065e-01, 1.750e-01, 1.655e-01, 2.555e-01, 2.390e-01,
       2.800e-02, 1.860e-01, 8.850e-02, 1.000e-01, 2.855e-01, 2.705e-01,
       2.505e-01, 3.335e-01, 1.970e-01, 3.270e-01, 2.450e-01, 3.345e-01,
       3.115e-01, 1.605e-01, 5.700e-02, 1.040e-01, 1.270e-01, 1.325e-01,
       8.150e-02, 1.795e-01, 2.260e-01, 2.790e-01, 2.205e-01, 2.070e-01,
       3.400e-02, 2.850e-02, 1.275e-01, 5.850e-02, 8.950e-02, 1.740e-01,
       4.950e-02, 9.500e-03, 5.000e-03, 3.690e-01, 3.055e-01, 2.045e-01,
       3.235e-01, 2.700e-01, 2.945e-01, 2.200e-02, 4.100e-02, 5.300e-02,
       1.665e-01, 4.000e-02, 1.610e-01, 5.650e-02, 4.200e-02, 4.085e-01,
       3.175e-01, 2.655e-01, 2.760e-01, 3.250e-01, 2.275e-01, 2.565e-01,
       3.065e-01, 1.520e-01, 1.730e-01, 5.550e-02, 7.400e-02, 2.455e-01,
       2.905e-01, 2.590e-01, 2.860e-01, 4.900e-01, 3.885e-01, 4.720e-01,
       3.920e-01, 2.460e-01, 2.995e-01, 3.015e-01, 2.440e-01, 2.735e-01,
       2.765e-01, 2.990e-01, 3.455e-01, 3.265e-01, 4.530e-01, 3.140e-01,
       2.920e-01, 3.695e-01, 3.365e-01, 2.875e-01, 3.135e-01, 1.370e-01,
       1.220e-01, 1.245e-01, 1.225e-01, 1.190e-01, 5.350e-02, 6.400e-02,
       1.760e-01, 1.390e-01, 1.985e-01, 1.045e-01, 1.820e-01, 2.215e-01,
       2.115e-01, 2.385e-01, 1.715e-01, 2.465e-01, 2.670e-01, 3.490e-01,
       1.990e-01, 3.580e-01, 1.230e-01, 2.000e-02, 2.030e-01, 2.435e-01,
       1.735e-01, 1.290e-01, 1.705e-01, 1.560e-01, 9.050e-02, 4.350e-02,
       5.500e-02, 6.450e-02, 1.380e-01, 5.250e-02, 7.700e-02, 1.360e-01,
       1.575e-01, 2.320e-01, 1.590e-01, 4.725e-01, 3.540e-01, 2.195e-01,
       3.045e-01, 1.200e-02, 3.500e-03, 3.035e-01, 2.665e-01, 1.405e-01,
       1.455e-01, 1.395e-01, 3.405e-01, 3.215e-01, 2.445e-01, 1.765e-01,
       2.120e-01, 2.370e-01, 1.615e-01, 1.810e-01, 2.235e-01, 2.595e-01,
       2.090e-01, 2.315e-01, 2.020e-01, 2.145e-01, 2.560e-01, 2.305e-01,
       2.470e-01, 1.570e-01, 2.040e-01, 1.265e-01, 3.650e-02, 2.150e-02,
       1.950e-02, 5.900e-02, 8.500e-03, 3.850e-02, 4.450e-02, 6.000e-03,
       2.550e-01, 6.600e-02, 9.250e-02, 6.950e-02, 5.500e-03, 1.555e-01,
       2.005e-01, 1.950e-01, 1.410e-01, 2.980e-01, 2.625e-01, 9.200e-02,
       1.630e-01, 1.260e-01, 1.005e-01, 1.090e-01, 8.750e-02, 2.010e-01,
       1.975e-01, 2.495e-01, 3.435e-01, 6.500e-02, 1.620e-01, 1.905e-01,
       7.600e-02, 5.800e-02, 2.975e-01, 1.530e-01, 1.825e-01, 2.255e-01,
       2.245e-01, 1.135e-01, 7.950e-02, 4.550e-02, 1.130e-01, 6.750e-02,
       8.250e-02, 3.550e-02, 7.050e-02, 4.700e-02, 3.350e-02, 4.250e-02,
       1.095e-01, 1.160e-01, 1.850e-01, 9.450e-02, 1.065e-01, 5.400e-02,
       1.365e-01, 8.400e-02, 1.050e-01, 9.900e-02, 2.400e-02, 4.650e-02,
       3.445e-01, 6.150e-02, 6.650e-02, 1.400e-01, 2.430e-01, 1.430e-01,
       1.480e-01, 2.600e-02, 9.400e-02, 2.325e-01, 2.125e-01, 1.425e-01,
       6.550e-02, 2.500e-03, 1.145e-01, 6.850e-02, 1.420e-01, 1.030e-01,
       9.000e-02, 2.750e-02, 1.900e-02, 1.150e-02, 4.000e-03, 2.280e-01,
       1.195e-01, 2.015e-01, 1.695e-01, 1.805e-01, 2.175e-01, 1.945e-01,
       4.805e-01, 4.105e-01, 1.500e-01, 3.005e-01, 3.680e-01, 2.360e-01,
       1.670e-01, 3.610e-01, 2.960e-01, 5.000e-02, 2.395e-01, 2.815e-01,
       1.700e-01, 1.505e-01, 1.375e-01, 2.060e-01, 1.650e-02, 2.025e-01,
       1.285e-01, 2.600e-01, 1.170e-01, 9.350e-02, 3.000e-02, 2.100e-02,
       4.800e-02, 1.185e-01, 1.855e-01, 2.400e-01, 2.155e-01, 3.300e-01,
       2.605e-01, 2.750e-01, 2.545e-01, 2.850e-01, 2.755e-01, 3.320e-01,
       3.150e-01, 2.910e-01, 3.415e-01, 3.910e-01, 3.220e-01, 3.775e-01,
       4.220e-01, 4.190e-01, 1.350e-02, 2.500e-02, 3.100e-02, 3.050e-02,
       4.400e-02, 6.900e-02, 7.450e-02, 7.200e-02, 7.800e-02, 8.350e-02,
       9.300e-02, 8.550e-02, 1.060e-01, 1.215e-01, 1.295e-01, 1.205e-01,
       1.340e-01, 2.290e-01, 2.745e-01, 2.200e-01, 2.645e-01, 2.580e-01,
       2.780e-01, 3.020e-01, 2.840e-01, 2.480e-01, 3.000e-01, 3.260e-01,
       3.420e-01, 3.555e-01, 3.080e-01, 3.120e-01, 3.225e-01, 3.310e-01,
       3.025e-01, 3.595e-01, 2.940e-01, 3.145e-01, 3.615e-01, 3.620e-01,
       4.015e-01, 3.960e-01, 4.200e-01, 5.225e-01, 4.185e-01, 3.830e-01,
       4.400e-01, 5.090e-01, 7.500e-03, 9.000e-03, 1.300e-02, 1.550e-02,
       1.750e-02, 2.700e-02, 8.650e-02, 7.350e-02, 1.120e-01, 1.490e-01,
       1.775e-01, 1.885e-01, 2.375e-01, 1.910e-01, 4.260e-01, 2.570e-01,
       2.365e-01, 2.500e-01, 2.715e-01, 2.900e-01, 2.110e-01, 3.390e-01,
       3.725e-01, 3.655e-01, 3.685e-01, 3.105e-01, 4.050e-01, 3.485e-01,
       3.715e-01, 3.355e-01, 4.180e-01, 3.070e-01, 3.810e-01, 4.070e-01,
       3.130e-01, 4.800e-01, 4.690e-01, 4.255e-01, 3.800e-01, 5.500e-01,
       4.585e-01, 5.195e-01, 5.130e-01, 4.985e-01, 3.300e-02, 6.250e-02,
       6.050e-02, 7.150e-02, 8.900e-02, 7.300e-02, 1.255e-01, 1.210e-01,
       1.350e-01, 1.445e-01, 1.545e-01, 1.650e-01, 1.305e-01, 1.840e-01,
       2.525e-01, 1.470e-01, 2.730e-01, 2.535e-01, 2.345e-01, 1.745e-01,
       2.335e-01, 1.955e-01, 3.195e-01, 2.685e-01, 3.450e-01, 2.950e-01,
       1.865e-01, 2.725e-01, 2.695e-01, 3.720e-01, 3.515e-01, 2.740e-01,
       3.780e-01, 3.585e-01, 3.735e-01, 3.865e-01, 3.525e-01, 3.125e-01,
       4.870e-01, 4.160e-01, 3.990e-01, 3.740e-01, 4.865e-01, 4.195e-01,
       3.890e-01, 5.640e-01, 4.345e-01, 4.600e-01, 4.460e-01, 5.190e-01,
       1.450e-02, 9.950e-02, 1.105e-01, 1.025e-01, 1.565e-01, 2.180e-01,
       2.300e-01, 2.150e-01, 2.085e-01, 2.350e-01, 3.245e-01, 3.650e-01,
       3.040e-01, 4.095e-01, 3.510e-01, 3.240e-01, 4.475e-01, 3.255e-01,
       3.325e-01, 3.665e-01, 3.630e-01, 4.130e-01, 4.270e-01, 3.970e-01,
       1.100e-02, 1.700e-02, 3.150e-02, 1.175e-01, 1.485e-01, 1.870e-01,
       1.660e-01, 2.380e-01, 1.980e-01, 1.515e-01, 1.925e-01, 2.410e-01,
       2.265e-01, 2.640e-01, 2.515e-01, 2.915e-01, 2.230e-01, 2.865e-01,
       3.090e-01, 2.925e-01, 4.205e-01, 2.880e-01, 3.370e-01, 2.810e-01,
       3.805e-01, 2.690e-01, 3.295e-01, 3.545e-01, 3.845e-01, 2.530e-01,
       3.200e-01, 3.110e-01, 3.095e-01, 3.305e-01, 2.930e-01, 3.750e-01,
       3.675e-01, 3.935e-01, 4.565e-01, 4.925e-01, 4.540e-01, 3.660e-01,
       4.425e-01, 4.030e-01, 5.185e-01, 4.825e-01, 4.210e-01, 6.415e-01,
       7.600e-01, 2.295e-01, 2.785e-01, 3.330e-01, 4.360e-01, 4.265e-01,
       9.650e-02, 9.750e-02, 1.335e-01, 1.645e-01, 2.285e-01, 2.885e-01,
       2.825e-01, 3.460e-01, 4.405e-01, 3.465e-01, 3.840e-01, 2.485e-01,
       3.030e-01, 2.955e-01, 2.675e-01, 2.845e-01, 3.790e-01, 4.020e-01,
       3.835e-01, 4.470e-01, 2.985e-01, 3.470e-01, 3.605e-01, 4.305e-01,
       4.915e-01, 1.850e-02, 2.300e-02, 6.800e-02, 1.540e-01, 1.770e-01,
       3.530e-01, 2.250e-02, 1.895e-01, 3.395e-01, 3.870e-01, 3.975e-01,
       4.480e-01, 4.755e-01, 2.650e-01, 2.105e-01, 3.705e-01, 1.000e-02,
       7.250e-02, 2.770e-01, 7.650e-02, 8.450e-02, 4.370e-01, 3.285e-01,
       4.650e-01, 4.920e-01, 4.075e-01, 3.600e-01, 3.765e-01, 2.835e-01,
       3.480e-01, 5.900e-01, 1.875e-01, 4.350e-01, 4.230e-01, 2.080e-01,
       3.430e-01, 1.180e-01, 1.800e-01, 3.710e-01, 1.115e-01, 2.630e-01,
       3.230e-01, 3.170e-01, 3.755e-01, 4.290e-01, 3.855e-01, 4.420e-01,
       5.005e-01, 5.120e-01, 4.820e-01, 1.995e-01, 3.520e-01, 5.265e-01,
       5.235e-01, 8.800e-02, 9.700e-02, 4.365e-01, 2.220e-01, 2.820e-01,
       3.770e-01, 3.375e-01, 3.730e-01, 4.170e-01, 3.210e-01, 5.250e-01,
       1.600e-02, 3.155e-01, 2.890e-01, 4.630e-01, 5.115e-01, 5.150e-02,
       3.190e-01, 4.055e-01, 4.655e-01, 4.780e-01, 4.740e-01, 3.905e-01,
       4.035e-01, 3.165e-01, 3.340e-01, 4.285e-01, 4.575e-01, 3.565e-01,
       3.795e-01, 3.570e-01, 7.000e-03, 4.065e-01, 3.985e-01, 3.205e-01,
       3.280e-01, 4.005e-01, 4.395e-01, 2.800e-01, 2.415e-01, 4.875e-01,
       7.900e-02, 4.505e-01, 3.410e-01, 5.750e-01, 3.850e-01, 3.645e-01,
       3.965e-01, 3.275e-01, 4.435e-01, 4.010e-01, 3.505e-01, 5.145e-01,
       2.795e-01, 4.100e-01, 3.940e-01, 5.745e-01, 4.025e-01, 4.215e-01,
       4.695e-01, 3.950e-01, 3.385e-01, 3.860e-01, 3.500e-01, 4.665e-01,
       3.820e-01, 4.045e-01, 4.110e-01, 2.490e-01, 3.640e-01, 4.385e-01,
       3.535e-01, 4.225e-01, 2.935e-01, 5.260e-01])

### **Univariate analysis**

# **Data Preparation**

In [61]:
df.head(1)

,ID,Clump_thickness,Uniformity_of_cell_size,Uniformity_of_cell_shape,Marginal_adhesion,Single_epithelial_cell_size,Bare_nuclei,Bland_chromatin,Normal_nucleoli,Mitoses,Diagnosis
0,M,0.455,0.365,0.095,0.514,0.2245,0.101,0.15,15,NaN,NaN

In [63]:
df['Diagnosis'] = df['Diagnosis'].map({2: 0, 4: 1}) # mapping the diagnosis to 0 and 1

In [69]:
counts = df['Diagnosis'].value_counts().sort_index()
counts

Series([], Name: count, dtype: int64)

# **Modeling**

# ***Evaluation**